import React from 'react';

function PrivacyPolicy() {
  return (
    <div class="text-white bg-slate-800 p-8">

  
  
    <h1 class="text-2xl font-bold mb-4">Privacy Policy</h1>
  
    <p class="text-lg leading-loose mb-8">
      Thank you for using our AI Image Generator app Pixely. This Privacy Policy explains how we collect, use, and disclose information when you use our services.
    </p>
  
    <h2 class="text-lg font-semibold mb-4">1. Information We Collect</h2>
    <p class="text-lg leading-loose mb-8">
      The App does not collect any personal data or information from its users. We do not require you to provide any personal information such as your name, email address, or phone number to use the App.
    </p>
  
    <h2 class="text-lg font-semibold mb-4">2. Information Generated by the App</h2>
    <p class="text-lg leading-loose mb-8">
      The App generates images based solely on the text input provided by the user. The text input is processed locally within the app, and no data is transmitted to our servers or stored externally. The images generated by the App are created solely for the user's use and are not stored or shared by the App.
    </p>
  
    <h2 class="text-lg font-semibold mb-4">3. Third-Party Services</h2>
    <p class="text-lg leading-loose mb-8">
      The App does not integrate with any third-party services or APIs that would require the transfer of user data.
    </p>
  
    <h2 class="text-lg font-semibold mb-4">4. Children's Privacy</h2>
    <p class="text-lg leading-loose mb-8">
      The App is not intended for use by children under the age of 13. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and believe that your child has provided personal information through the App, please contact us immediately, and we will delete such information from our records.
    </p>
  
    <h2 class="text-lg font-semibold mb-4">5. Data Security</h2>
    <p class="text-lg leading-loose mb-8">
      We take the security of your information seriously. The App employs industry-standard security measures to protect against the unauthorized access, alteration, disclosure, or destruction of data. However, please be aware that no method of transmission over the internet or electronic storage is 100% secure, and we cannot guarantee absolute security.
    </p>
  
    <h2 class="text-lg font-semibold mb-4">6. Changes to This Privacy Policy</h2>
    <p class="text-lg leading-loose mb-8">
      We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
    </p>
  
    <h2 class="text-lg font-semibold mb-4">7. Contact Us</h2>
    <p class="text-lg leading-loose mb-8">
      If you have any questions or concerns about this Privacy Policy or our practices regarding your information, please contact us at <a href="mailto:services@geneticraft.fun" class="text-blue-500 hover:text-blue-700">services@geneticraft.fun</a>.
    </p>
  
    <p class="text-sm text-gray-400 mt-8">
      By using the App, you agree to the collection and use of information in accordance with this Privacy Policy.
    </p>
  </div>
  

  );
}

export default PrivacyPolicy;
